# Generated by Django 2.2 on 2020-03-26 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_templates', '0003_emailtemplate_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('spreadsheet_id', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('email_separator', models.CharField(max_length=1)),
                ('email', models.TextField(blank=True, null=True)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spreadheets', to='email_templates.EmailTemplate', verbose_name='Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'spreadsheet',
                'verbose_name_plural': 'spreadsheets',
            },
        ),
    ]