# Generated by Django 2.2 on 2020-03-31 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spreadsheets', to='email_templates.EmailTemplate', verbose_name='Template'),
        ),
    ]
