# Generated by Django 2.2 on 2020-04-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20200331_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='bcc',
            field=models.TextField(blank=True, null=True, verbose_name='BCC'),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='email_separator',
            field=models.CharField(max_length=1, verbose_name='Email Separator'),
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='spreadsheet_id',
            field=models.TextField(verbose_name='Spreadsheet ID'),
        ),
    ]
