version: '3'
services:
  db:
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
  web:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    command: bash -c "python /code/manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/code
    expose:
      - 8000
   
    depends_on:
      - db
      - redis
  celery:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    command: celery -A config worker -l info
    expose:
      - "6379"
    volumes:
      - ./:/code
    depends_on:
      - redis
  nginx:
    restart: always
    image: nginx:latest
    
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d
      - ./:/code
    depends_on:
      - web
volumes:
  postgres_data:
