# Generated by Django 2.2 on 2020-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
