# Generated by Django 2.2 on 2020-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_auto_20200318_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='html',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
