# Generated by Django 2.2 on 2020-03-26 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_templates', '0003_emailtemplate_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_email', models.CharField(max_length=120)),
                ('smtp_host', models.CharField(max_length=120)),
                ('smtp_port', models.IntegerField()),
                ('smtp_username', models.CharField(max_length=120)),
                ('smtp_password', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
