# Generated by Django 2.2 on 2020-03-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0004_emailsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name_plural': 'email settings'},
        ),
    ]
