# Generated by Django 2.2 on 2020-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0005_auto_20200326_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='test_email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
