# Generated by Django 2.2 on 2020-03-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0006_auto_20200326_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='smtp_from_email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
