# Generated by Django 2.2 on 2020-04-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0007_emailsettings_smtp_from_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name': 'email settings', 'verbose_name_plural': 'email settings'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'email template', 'verbose_name_plural': 'email templates'},
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_from_email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='From email'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='SMTP Host'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='SMTP Password'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='SMTP Port'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='SMTP Username'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='test_email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Test Email'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html',
            field=models.TextField(verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Template'),
        ),
    ]
